Repository notyumin/SimpCity, pull requests merged in 2022-01, with the labels that each got.

#31 Feature/issue 4 - Code update for printing dynamically sized boards
  .github/workflows/CI - Developers.yml
  simpCity.py
  test_simpCity.py
Labels: size_m

#27 Feature/issue 17
  .github/workflows/CI - Developers.yml
  simpCity.py
  test_simpCity.py
Labels: size_m

#37 Re-arranged workflow order.
  .github/workflows/CI - Developers.yml
Labels: size_s

#35 Feature/issue 22 - Score Calculation
  simpCity.py
  test_simpCity.py
Labels: size_m

#28 Feature/issue 18 20
  .github/workflows/CI - Developers.yml
  simpCity.py
  test_simpCity.py
Labels: size_m

#40 Workflow updates - Added code coverage
  .coveragerc
  .github/workflows/CI - Developers.yml
  README.md
Labels: size_s

#38 Feature/issue 19
  .github/workflows/CI - Developers.yml
  simpCity.py
Labels: size_s

#43 Fixed bug in Feature/issue 18 20
  simpCity.py
Labels: size_xs

#48 Workflow update - set min coverage to 40% and 10% diff between commits
  codecov.yml
Labels: size_s

#47 Feature/issue 17
  simpCity.py
  test_simpCity.py
Labels: size_m

#44 Feature/issue 21 16
  .github/workflows/CI - Developers.yml
  codecov.yml
  high4.pickle
  high5.pickle
  high6.pickle
  high7.pickle
  save.pickle
  simpCity.py
  test_simpCity.py
Labels: size_m

#49 Refactor
  component_Logic.py
  simpCity.py
  test_simpCity.py
Labels: size_l
